source 'http://rubygems.org'

gem 'sinatra'
gem 'omniauth'
gem 'omniauth-github'
gem 'mongoid', '~> 3.0'
gem 'bson_ext'
gem 'httparty'
gem 'haml'
gem 'airbrake'
gem 'will_paginate'
gem 'json'
gem 'i18n'
gem 'sass'
gem 'RedCloth'
gem 'rake'
gem 'whenever'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'gh'
gem 'haml-contrib'

gem 'rspec'

group :test do
  gem 'rack-test'
  gem 'steak', '~> 1.0'
  gem 'capybara'
  gem 'launchy'
  gem 'fuubar'
  gem 'fakeweb'
  gem 'machinist_mongo'
end
